# Generated by Django 5.2.8 on 2025-12-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_address_created_basket_created_brand_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.IntegerField(choices=[(0, 'Europe'), (1, 'North America'), (2, 'Asia'), (3, 'Oceania'), (4, 'Middle East'), (5, 'South America'), (6, 'Central America'), (7, 'Caribbean'), (8, 'Africa')]),
        ),
    ]
