# Generated by Django 5.2.8 on 2025-12-02 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_country_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='gender',
            field=models.CharField(choices=[('mens', 'Mens'), ('womens', 'Womens'), ('unisex', 'Unisex')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
