# Generated by Django 5.2.8 on 2025-12-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_brand_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('mens', 'Mens'), ('womens', 'Womens')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='primary_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
