# Generated by Django 5.2.8 on 2025-12-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_contact_email_alter_contact_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='display',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.CharField(choices=[('news', 'News'), ('blog', 'Blog'), ('promo', 'Promotion'), ('trend_watch', 'Trend Watch'), ('collabs', 'Collabs'), ('sustainability', 'Sustainability'), ('sneakers', 'Sneakers'), ('product_updates', 'Product Updates')], max_length=50),
        ),
    ]
