# Generated by Django 5.2.8 on 2025-12-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_article_display_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactus',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
