# Generated by Django 5.2.8 on 2025-12-03 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_contactus_email_alter_contactus_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('nonbinary', 'Non-binary'), ('other', 'Other')], max_length=16),
        ),
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mx', 'Mx'), ('Dr', 'Dr')], max_length=16),
        ),
    ]
