# Generated by Django 5.2.8 on 2025-12-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_contact_gender_contact_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('nonbinary', 'Non-binary'), ('other', 'Other')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Ms', 'Ms'), ('Mx', 'Mx'), ('Dr', 'Dr')], max_length=16, null=True),
        ),
    ]
